### ISSUE TITLE
Module does not load

### ISSUE THREAD

**Issue by storkpkp** [esteban-mallen/homebridge-adt-smart-security#7]
[7/28/2019, 2:27:28 PM] ---
[7/28/2019, 2:27:29 PM] ====================
[7/28/2019, 2:27:29 PM] ERROR LOADING PLUGIN homebridge-adt-smart-security:
[7/28/2019, 2:27:29 PM] Error: Cannot find module 'ip'
Require stack:
- /usr/local/lib/node_modules/homebridge-adt-smart-security/lib/FFMPEG.js
- /usr/local/lib/node_modules/homebridge-adt-smart-security/lib/camera.js
- /usr/local/lib/node_modules/homebridge-adt-smart-security/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-adt-smart-security/lib/FFMPEG.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-adt-smart-security/lib/camera.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-adt-smart-security/index.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
[7/28/2019, 2:27:29 PM] ====================

I get the following error

**Comment by insanelysick** [comment]
Same issue here along with this

[9/28/2019, 4:03:39 PM] Error: The requested platform 'ADT' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by insanelysick** [comment]
runtime dependancy 'ip' not specified in package.json run "npm install ip" to install the module.

Now im hitting this 

`Initialization failed TypeError: Cannot read property 'substring' of undefined
    at request.then (/homebridge/node_modules/homebridge-adt-smart-security/lib/adt.js:151:57)
    at tryCatcher (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-adt-smart-security/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

**Comment by jonmoore-pulse** [comment]
I am seeing this:
[6/4/2020, 10:06:35] Error loading platform requested in your config.json at position 4
[6/4/2020, 10:06:35] Error: The requested platform 'ADT' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

Any chance of a fix @esteban-mallen ?

**Comment by jonb23** [comment]
same errors as above.
